"""
PromptForge - ⚒️ AI绘画提示词锻造工具
"""

from .nodes_config import NODE_CLASS_MAPPINGS as CONFIG_NODES
from .nodes_character import NODE_CLASS_MAPPINGS as CHARACTER_NODES
from .nodes_llm import NODE_CLASS_MAPPINGS as LLM_NODES
from .nodes_prompt import NODE_CLASS_MAPPINGS as PROMPT_NODES

from .nodes_config import NODE_DISPLAY_NAME_MAPPINGS as CONFIG_DISPLAY
from .nodes_character import NODE_DISPLAY_NAME_MAPPINGS as CHARACTER_DISPLAY
from .nodes_llm import NODE_DISPLAY_NAME_MAPPINGS as LLM_DISPLAY
from .nodes_prompt import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CONFIG_NODES)
NODE_CLASS_MAPPINGS.update(CHARACTER_NODES)
NODE_CLASS_MAPPINGS.update(LLM_NODES)
NODE_CLASS_MAPPINGS.update(PROMPT_NODES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CONFIG_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CHARACTER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(LLM_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPT_DISPLAY)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
